train:
  env: DrivingPLE-v0
  env_config:
    switch_prob: 0.1
    switch_duration: 50
    collision_penalty: -100
    time_reward_proportion: 1
    normalize_reward: true
    time_limit: 5000
test:
  env: DrivingPLE-v0
  env_config:
    switch_prob: 0.2
    switch_duration: 50
    collision_penalty: -100
    time_reward_proportion: 1
    normalize_reward: true
    time_limit: 5000