name: lifelong_rl
dependencies:
    - python=3.7
    - patchelf
    - swig
    - pip:
        - atari-py==0.2.6
        - backcall==0.1.0
        - boto3==1.13.1
        - botocore==1.16.1
        - Box2D==2.3.10
        - Box2D-kengz==2.3.3
        - certifi==2020.4.5.1
        - cffi==1.14.0
        - chardet==3.0.4
        - click==7.1.2
        - cloudpickle==1.3.0
        - cycler==0.10.0
        - Cython==0.29.17
        - decorator==4.4.2
        - docutils==0.15.2
        - fasteners==0.15
        - Flask==1.1.2
        - future==0.18.2
        - gitdb==4.0.4
        - gitdb2==4.0.2
        - GitPython==3.1.1
        - glfw==1.11.0
        - gtimer==1.0.0b5
        - gym==0.17.1
        - idna==2.9
        - imageio==2.8.0
        - ipdb==0.13.2
        - ipython==7.14.0
        - ipython-genutils==0.2.0
        - itsdangerous==1.1.0
        - jedi==0.17.0
        - Jinja2==2.11.2
        - jmespath==0.9.5
        - joblib==0.14.1
        - kiwisolver==1.2.0
        - llvmlite==0.32.0
        - lockfile==0.12.2
        - Mako==1.1.2
        - MarkupSafe==1.1.1
        - matplotlib==3.2.1
        - monotonic==1.5
        - mujoco-py==2.0.2.9
        - numba==0.49.0
        - numpy==1.18.3
        - packaging==20.3
        - pandas==1.0.3
        - parso==0.7.0
        - pexpect==4.8.0
        - pickleshare==0.7.5
        - Pillow==7.1.2
        - plotly==4.6.0
        - prompt-toolkit==3.0.5
        - ptyprocess==0.6.0
        - pycparser==2.20
        - pygame==1.9.6
        - pyglet==1.5.0
        - Pygments==2.6.1
        - PyOpenGL==3.1.5
        - pyparsing==2.4.7
        - python-dateutil==2.8.1
        - pytz==2020.1
        - requests==2.23.0
        - retrying==1.3.3
        - s3transfer==0.3.3
        - scipy==1.4.1
        - seaborn==0.10.1
        - simplegeneric==0.8.1
        - sip==5.2.0
        - six==1.14.0
        - smmap==3.0.2
        - toml==0.10.0
        - torch==1.4.0
        - torchvision==0.5.0
        - traitlets==4.3.3
        - urllib3==1.25.9
        - wcwidth==0.1.9
        - Werkzeug==1.0.1
