run: IMPALA
stop:
  timesteps_total: 3000000
config:
  rollout_fragment_length: 50
  train_batch_size: 500
  num_workers: 128
  num_envs_per_worker: 5
  clip_rewards: True
  lr_schedule: [
  [0, 0.0005],
  [20000000, 0.000000000001],
  ]